### ISSUE TITLE
Implement `From<Metadata>` and `From<Manifest>` for `PackageFullName` and `PackageID`.

### ISSUE THREAD

**Issue by Arignir** [raven-os/nest#68]
There's some missed opportunities to implement `From` for both `PackageFullName` and `PackageID`, which adds boilerplate code for software using the libnest.

**Comment by doom** [comment]
Since `Manifest` is now repository-agnostic and `PackageManifest` does not represent a single version, these implementations of `From` don't make sense anymore for `PackageID`.

However, an implementation of `From<PackageManifest>` for `PackageFullName` would still be nice.
